### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by zhengshengjie666** [ben221199/WAPI#17]
//Connection arguments
        byte[] edge_routing_info = null;
        KeyPair client_static_keypair = null;
        PublicKey server_static_key = null;
        WA4Protos.ClientPayload payload = null;

        //Create connection
        Connection conn = new Connection("g.whatsapp.net",443)
                .setEdgeRoutingInfo(edge_routing_info)
                .setS(client_static_keypair)
                .setRS(server_static_key)
                .setPayload(payload);

        //Start connection
        conn.start();

        //Get IO
        FunInputStream in = conn.getInputStream();
        FunOutputStream out = conn.getOutputStream();

Exception in thread "main" java.lang.NullPointerException
	at nl.ben221199.wapi.Connection.doHandshakeXX(Connection.java:110)
	at nl.ben221199.wapi.Connection.doHandshake(Connection.java:79)
	at nl.ben221199.wapi.Connection.start(Connection.java:67)
	at WaConnectTest.main(WaConnectTest.java:31)

我不知道该怎么办了

**Comment by ben221199** [comment]
You do not initiate the following variables:
```Java
byte[] edge_routing_info = null;
KeyPair client_static_keypair = null;
PublicKey server_static_key = null;
WA4Protos.ClientPayload payload = null;
```
So, you are passing `null`-values to the connection.
First give this variables some value.
