### ISSUE TITLE
Yowsup group

### ISSUE THREAD

**Issue by luisdesouza** [ben221199/WAPI#6]
I've create a telegram group to discuss about Yowsup.
Would you like to participate?
This is the address: https://t.me/YowsupGroup

**Comment by ben221199** [comment]
We have 2 Discord servers to chat in:

Yowsup: https://discord.gg/KCAs9Pq57N
Yowsup Support: https://discord.com/invite/Wa7QSxZ

Btw, this project is called WAPI and not Yowsup, so yowsup-related issues are not allowed here.
